spring.application.name: kitsune-backend

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:8081/dev?useSSL=false}
    username: ${DATABASE_USER:spring}
    password: ${DATABASE_PASS:secret}
  flyway:
    baseline-on-migrate: true
    enabled: ${FLYWAY_ENABLED:true}


server:
  port: 8080

config:
  invidious:
    endpoints: "https://inv.tux.pizza,https://invidious.jing.rocks,https://invidious.incogniweb.net,https://vid.puffyan.us"
