spring.application.name: kitsune-backend

spring:
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USER}"
    password: "${DATABASE_PASS}"
  flyway:
    baseline-on-migrate: true
    enabled: "${FLYWAY_ENABLED:true}"
  devtools:
    add-properties: false


server:
  port: 8080

config:
  invidious:
    endpoints: "https://inv.tux.pizza,https://invidious.jing.rocks,https://invidious.incogniweb.net,https://vid.puffyan.us"
