spring.application.name: kitsune-backend

spring:
  datasource:
    url: "${DATABASE_URL:jdbc:postgresql://localhost:8081/dev?useSSL=false}"
    username: "${DATABASE_USER:spring}"
    password: "${DATABASE_PASS:secret}"
  flyway:
    baseline-on-migrate: true
    enabled: "${FLYWAY_ENABLED:true}"
  devtools:
    add-properties: false


server:
  port: 8080
  servlet:
    context-path: /api

config:
  invidious:
    endpoints: "https://invidious.fdn.fr,https://inv.tux.pizza,https://invidious.flokinet.to,https://invidious.privacydev.net,https://inv.nadeko.net,https://invidious.nerdvpn.de,https://invidious.protokolla.fi,https://invidious.private.coffee,https://invidious.jing.rocks,https://invidious.perennialte.ch,https://yt.artemislena.eu,https://invidious.materialio.us,https://inv.in.projectsegfau.lt,https://invidious.reallyaweso.me,https://iv.datura.network,https://invidious.darkness.services,https://yt.drgnz.club,https://yewtu.be,https://invidious.incogniweb.net,https://iv.melmac.space,https://invidious.drgns.space,https://invidious.privacyredirect.com"
  holodex:
    endpoint: https://holodex.net/api/v2
    api_key: "${HOLODEX_API_KEY}"
  timing:
    # TODO: make IntelliJ IDEA not complain about this
    schedule: "${TRACK_SCHEDULE:0 */5 * * * *}"
